/**
 * este se podria convertir en el unico buscador necesario
 * es solo en el parent identificar cual es, y cuando se identifique cambie la 
 * orden al dar click en el boton aceptar
 * ejemplo:
 * si el buscador lo lanzamos desde servicios, desde cliente, u otra ubicacion, que 
 * nos diga cual fue y poder ejecutar lo requerido
 */

package View;
import Task.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Gomez
 */
public class JDialog_Bus_Cli extends javax.swing.JDialog {
    Conexion con;
    DefaultTableModel modelo;
    String pariente;
    JFrame_Servicio service;
    /**
     * Creates new form JDialog_Bus_Cli
     * @param parent
     * @param modal
     */
    public JDialog_Bus_Cli(javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JDialog_Bus_Cli(javax.swing.JFrame parent, boolean modal, Conexion con) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        pariente = parent.getTitle();
        this.con = con;
        modelo = (DefaultTableModel) jTable1.getModel();
        switch (pariente) {
            case "Home":
                vertodo();
                formato_ancho();
                break;
            case "Servicio":
                jButton5.setVisible(false);
                break;
            case "Agenda":
                jButton5.setVisible(false);
            case "Aceite":
                jButton5.setVisible(false);
            break;
        }
    }
    public JDialog_Bus_Cli(javax.swing.JDialog parent, boolean modal, Conexion con) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pariente = parent.getTitle();
        this.con = con;
        modelo = (DefaultTableModel) jTable1.getModel();
        jButton5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Moto", "Empresa", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificación", "Nombre" }));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifier_1.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Apellido", "Placa", "Nit", "Razon Social"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton2KeyTyped(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton3KeyTyped(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book_open.png"))); // NOI18N
        jButton4.setText("Ver Mas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton4KeyTyped(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disconnect.png"))); // NOI18N
        jButton5.setText("Recargar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton5KeyTyped(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo2Reducido2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem() == "Cliente"){
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificación", "Nombre", " ", " " }));
        }
        if(jComboBox1.getSelectedItem() == "Moto"){
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Placa", " ", " ", " " }));
        }
        if(jComboBox1.getSelectedItem() == "Empresa"){
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIT", "Razón Social", " ", " " }));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //se toma en cuenta que siempre hay una moto asociada a un cliente
        //SI VIENE DE HOME O SERVICIO....con.cargar("SELECT id, tipo_id, nombre, apellido1, tel1, cel1 FROM cliente", modelo);
        if(jComboBox1.getSelectedItem() == "Cliente"){
            if(jComboBox2.getSelectedItem() == "Identificación"){
                //se hace la comprobacion de si el cliente tiene asociacion con alguna empresa
                //hay_empresa(bus_cli bc) 
                bus_cli bc = new bus_cli();
                if(!"".equals(txtBuscar.getText())){
                    bc.setId(Double.parseDouble(txtBuscar.getText()));
                }
                //verificamos que el cliente tenga o no alguna empresa.
                //si la tiene ejecuta el comando para que muestre los datos de esta
                //si no la tiene, ejecuta el comando que la exime
                if(con.hay_empresa(bc) == true){
                    con.cargar("SELECT cliente.id, cliente.nombre, cliente.apellido1, moto.placa, empresa.nit, empresa.razon_social \n" +
                        "FROM cliente INNER JOIN moto on cliente.id = moto.id \n" +
                        "INNER JOIN empresa on cliente.nit = empresa.nit \n" +
                        "where cliente.id = '"+txtBuscar.getText()+"'", modelo);
                }else{
                    con.cargar("SELECT cliente.id, cliente.nombre, cliente.apellido1, moto.placa\n" +
                        "FROM cliente INNER JOIN moto on cliente.id = moto.id \n" +
                        "where cliente.id =  '"+txtBuscar.getText()+"'", modelo);
                    JOptionPane.showMessageDialog(this, "El cliente no tiene asociada ninguna empresa o no existe");
                }
            }
            if(jComboBox2.getSelectedItem() == "Nombre"){
                //hay_empresa_nombre
                bus_cli bc = new bus_cli();
                bc.setNombre(txtBuscar.getText());
                if(con.hay_empresa_nombre(bc) == true){
                     con.cargar("SELECT cliente.id, cliente.nombre, cliente.apellido1, moto.placa, empresa.nit, empresa.razon_social \n" +
                        "FROM cliente INNER JOIN moto on cliente.id = moto.id \n" +
                        "INNER JOIN empresa on cliente.nit = empresa.nit \n" +
                        "where cliente.nombre LIKE('%"+txtBuscar.getText()+"%')", modelo);
                }else{
                    con.cargar("select cliente.id, cliente.nombre, cliente.apellido1, moto.placa\n" +
                    "from cliente inner join moto on cliente.id = moto.id \n" +
                    "where cliente.nombre LIKE('%"+txtBuscar.getText()+"%')", modelo);
                    JOptionPane.showMessageDialog(this, "El cliente no tiene asociada ninguna empresa o no existe");
                }
               
            }
            //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Identificación", "Nombre", " ", " " }));
        }
        if(jComboBox1.getSelectedItem() == "Moto"){
            if(jComboBox2.getSelectedItem() == "Placa"){
            //
                //se hace la comprobacion de si el cliente tiene asociacion con alguna empresa
                //hay_empresa(bus_cli bc) 
                bus_cli bc = new bus_cli();
                bc.setPlaca(txtBuscar.getText());
                //verificamos que el cliente tenga o no alguna empresa.
                //si la tiene ejecuta el comando para que muestre los datos de esta
                //si no la tiene, ejecuta el comando que la exime
                if(con.hay_empresa_moto(bc) == true){
                    con.cargar("SELECT cliente.id, cliente.nombre, cliente.apellido1, moto.placa, empresa.nit, empresa.razon_social \n" +
                        "FROM cliente INNER JOIN moto on cliente.id = moto.id \n" +
                        "INNER JOIN empresa on cliente.nit = empresa.nit \n" +
                        "where moto.placa = '"+txtBuscar.getText()+"'", modelo);
                }else{
                    con.cargar("SELECT cliente.id, cliente.nombre, cliente.apellido1, moto.placa\n" +
                        "FROM cliente INNER JOIN moto on cliente.id = moto.id \n" +
                        "where moto.placa = '"+txtBuscar.getText()+"'", modelo);
                    JOptionPane.showMessageDialog(this, "El cliente no tiene asociada ninguna empresa o no existe");
                }
            }
            //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Placa", " ", " ", " " }));
        }
        if(jComboBox1.getSelectedItem() == "Empresa"){
            if(jComboBox2.getSelectedItem() == "NIT"){
                bus_cli bc = new bus_cli();
                bc.setNit(txtBuscar.getText());
                if(con.hay_empresa_emp(bc) == true){
                    con.cargar("select cliente.id, cliente.nombre, cliente.apellido1, moto.placa, empresa.nit, empresa.razon_social \n" +
                        "from cliente inner join moto on cliente.id = moto.id \n" +
                        "inner join empresa on cliente.nit = empresa.nit \n" +
                        "where empresa.nit = '"+txtBuscar.getText()+"'", modelo);
                }else{
                    JOptionPane.showMessageDialog(this, "La empresa solicitada no existe. Verifique el NIT");
                    modelo.setRowCount(0);
                }
            }
            if(jComboBox2.getSelectedItem() == "Razón Social"){
                bus_cli bc = new bus_cli();
                bc.setRazon_social(txtBuscar.getText());
                if(con.hay_empresa_rz(bc) == true){
                    con.cargar("select cliente.id, cliente.nombre, cliente.apellido1, moto.placa, empresa.nit, empresa.razon_social \n" +
                        "from cliente inner join moto on cliente.id = moto.id \n" +
                        "inner join empresa on cliente.nit = empresa.nit \n" +
                        "where empresa.razon_social = '"+txtBuscar.getText()+"'", modelo);
                }else{
                    JOptionPane.showMessageDialog(this, "La empresa solicitada no existe. Verifique el Nombre");
                    modelo.setRowCount(0);
                }
            }
            //jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIT", "Razón Social", " ", " " }));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // si el parent es home haga esto
        switch (pariente) {
            case "Home":
                this.dispose();
                break;
            case "Servicio":
                //que pregunte por la fila seleccionada
                int fil_sel = jTable1.getSelectedRow();
                if(fil_sel < 0){
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
                }else{
                  //cuando tenga le cliente sleeccionado, debere cargar los datos al objeto bus_cli
                    //luego de alli se recuperaran los valores y se le psara al jframe_servicio
                    int columncount = jTable1.getColumnCount();
                    if(columncount <= 4){
                        JFrame_Servicio.jLabel7.setText(jTable1.getValueAt(fil_sel, 0).toString());
                        JFrame_Servicio.jLabel6.setText(jTable1.getValueAt(fil_sel, 1).toString());
                        JFrame_Servicio.jLabel10.setText(jTable1.getValueAt(fil_sel, 2).toString());
                        JFrame_Servicio.txtPlaca.setText(jTable1.getValueAt(fil_sel, 3).toString());
                        JFrame_Servicio.jLabel1.setText("");
                        JFrame_Servicio.jLabel9.setText(""); 
                        this.dispose();
                    }
                    if(columncount > 4){
                        JFrame_Servicio.jLabel7.setText(jTable1.getValueAt(fil_sel, 0).toString());
                        JFrame_Servicio.jLabel6.setText(jTable1.getValueAt(fil_sel, 1).toString());
                        JFrame_Servicio.jLabel10.setText(jTable1.getValueAt(fil_sel, 2).toString());
                        JFrame_Servicio.txtPlaca.setText(jTable1.getValueAt(fil_sel, 3).toString());
                        JFrame_Servicio.jLabel1.setText(jTable1.getValueAt(fil_sel, 4).toString());
                        JFrame_Servicio.jLabel9.setText(jTable1.getValueAt(fil_sel, 5).toString()); 
                        this.dispose();
                    }
                }
                break;
            case "Agenda":
                int fil_sel2 = jTable1.getSelectedRow();
                if(fil_sel2 < 0){
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
                }else{
                    JDialog_Agenda.txtCliente.setText(jTable1.getValueAt(fil_sel2, 3).toString());
                    JDialog_Agenda.txtNombre.setText(jTable1.getValueAt(fil_sel2, 1).toString());
                    this.dispose();
                }
                break;
            case "Aceite":
                int fil_sel3 = jTable1.getSelectedRow();
                if(fil_sel3 < 0){
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente");
                }else{
                    JDialog_Aceite.txtCliente.setText(jTable1.getValueAt(fil_sel3, 3).toString());
                    JDialog_Aceite.txtNombre.setText(jTable1.getValueAt(fil_sel3, 1).toString());
                    this.dispose();
                }
            break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
            this.dispose();
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        vertodo();
        formato_ancho();
    }//GEN-LAST:event_jButton5ActionPerformed
    // este me carga el Cliente_General. y alli se cargan TODOS los datos del cliente
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int fil_sel = jTable1.getSelectedRow();
        if(fil_sel < 0){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente para acceder a mas opciones");
        }else{
            //se coge el id del cliente seleccionado y se le manda al dialog del cliente general para ver todos sus datos
            int ced = Integer.parseInt(jTable1.getValueAt(fil_sel, 0).toString());
            JDialog_Cliente_General cli_gral = new JDialog_Cliente_General(this, true, con, ced);
            cli_gral.setVisible(true);            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
               jButton1.requestFocus();
        }
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
               jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyTyped

    private void jButton2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
               jButton2.doClick();
        }
    }//GEN-LAST:event_jButton2KeyTyped

    private void jButton4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
               jButton4.doClick();
        }
    }//GEN-LAST:event_jButton4KeyTyped

    private void jButton5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
               jButton5.doClick();
        }
    }//GEN-LAST:event_jButton5KeyTyped

    private void jButton3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
               jButton3.doClick();
        }
    }//GEN-LAST:event_jButton3KeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_Bus_Cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_Bus_Cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_Bus_Cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Bus_Cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_Bus_Cli dialog = new JDialog_Bus_Cli(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void vertodo() {
        con.cargar("SELECT id, tipo_id, nombre, apellido1, tel1, cel1 FROM cliente", modelo);
    }
    
    private void formato_ancho(){
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(116);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(116);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(97);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(96);
    }
}
