/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Task.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Gomez
 */
public class JDialog_Moto extends javax.swing.JDialog {

    Conexion con;
    
    int contador = 0;
    //protected String placa;
    //SE GUARDAN EN TEMPORALES: LAS RUTAS ABSOLUTAS, LAS EXTENCIONES
    String path1, path2, path3, path4; //SE ALMACENAN LAS RUTAS DE LAS IMAGENES 
    String ext1, ext2, ext3, ext4;
    //private final String directorio = "D:\\TALLER\\FOTOS\\MOTOSOFT\\";//LUGAR DONDE SE ALMACENAN LAS FOTOS
    //ejemploString dir = System.getProperty("user.dir");
    private final String directorio = System.getProperty("user.dir") + "\\TecSoft\\imagenes\\";
    
    String letras = "abcdefghijklmnñopqrstuvwxyz ";
    String numeros = "1234567890";
    //String dir = "D:\\TALLER\\FOTOS\\MOTOSOFT";//DONDE INICIA LA BUSQUEDA. POR DEFECTO 
    String dir = directorio;
    
    String padre;//para cargar imagenes al sar click 
   // String dir_abso;
    
    /**
     * Creates new form JDialog_Moto
     * @param parent
     * @param modal
     */
    public JDialog_Moto(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JDialog_Moto(javax.swing.JDialog parent, boolean modal, Conexion con) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        centrar();
        txtPlaca.requestFocus();
        this.con = con; 
        cerrarControlado();
    }
    public final void centrar(){
        Dimension pantalla = this.getToolkit().getScreenSize();
        this.setLocation(pantalla.width /2 - this.getWidth() / 2, pantalla.height / 2 - this.getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnBu_Ima2 = new javax.swing.JButton();
        btnBu_Ima3 = new javax.swing.JButton();
        btnBu_Ima4 = new javax.swing.JButton();
        txtImg1 = new javax.swing.JTextField();
        lblImg1 = new javax.swing.JLabel();
        txtImg2 = new javax.swing.JTextField();
        lblImg2 = new javax.swing.JLabel();
        txtImg3 = new javax.swing.JTextField();
        lblImg3 = new javax.swing.JLabel();
        txtImg4 = new javax.swing.JTextField();
        lblImg4 = new javax.swing.JLabel();
        btnBu_Ima1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Moto"));

        jLabel2.setText("Placa:");

        jLabel3.setText("Marca:");

        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPlacaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });

        jLabel4.setText("Linea:");

        jLabel5.setText("Color:");

        jLabel6.setText("Modelo:");

        jLabel7.setText("Cilindraje:");

        txtLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLineaKeyTyped(evt);
            }
        });

        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });

        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });

        txtCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCCKeyTyped(evt);
            }
        });

        jLabel1.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLinea)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        btnBu_Ima2.setText("Cargar Imagen 2");
        btnBu_Ima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBu_Ima2ActionPerformed(evt);
            }
        });

        btnBu_Ima3.setText("Cargar Imagen 3");
        btnBu_Ima3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBu_Ima3ActionPerformed(evt);
            }
        });

        btnBu_Ima4.setText("Cargar Imagen 4");
        btnBu_Ima4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBu_Ima4ActionPerformed(evt);
            }
        });

        lblImg1.setText("Imagen 1");
        lblImg1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg1MouseClicked(evt);
            }
        });

        lblImg2.setText("Imagen 2");
        lblImg2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg2MouseClicked(evt);
            }
        });

        lblImg3.setText("Imagen 3");
        lblImg3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImg3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg3MouseClicked(evt);
            }
        });

        lblImg4.setText("Imagen 4");
        lblImg4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImg4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg4MouseClicked(evt);
            }
        });

        btnBu_Ima1.setText("Cargar Imagen 1");
        btnBu_Ima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBu_Ima1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnBu_Ima1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnBu_Ima2))
                            .addComponent(lblImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImg2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblImg3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnBu_Ima3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnBu_Ima4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblImg4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(txtImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBu_Ima2)
                    .addComponent(btnBu_Ima1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImg3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBu_Ima4)
                    .addComponent(btnBu_Ima3))
                .addContainerGap())
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnGuardarKeyTyped(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalirKeyTyped(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo2Reducido2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir))
                        .addGap(47, 47, 47))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(guardar()){
           guardar_img_dir();
           contador += 1;
            if(JOptionPane.showConfirmDialog(this, "¿Desea salir ahora mismo?", 
                "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
                this.dispose();
            }
        }else{
           contador = 0;
        }     
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       confirmarSalida();        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBu_Ima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBu_Ima1ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File(dir));
        fc.setFileFilter(new FileNameExtensionFilter("Archivos de Imagen", "jpg", "jpeg", "png", "gif"));
        fc.setDialogTitle("Buscador de imagenes");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        int status = fc.showOpenDialog(this);
        if(status == JFileChooser.APPROVE_OPTION){
            File archivo = fc.getSelectedFile();
            if(archivo != null){
                //SE AGREGA LA IMAGEN SELECCIONADA AL ICONO DEL LABEL CORRESPONDIENTE
                ImageIcon icon = new ImageIcon(archivo.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblImg1.getWidth(), lblImg1.getHeight(), Image.SCALE_DEFAULT));
                lblImg1.setText(null);
                lblImg1.setIcon(icono);
                //SE ALMACENA LA RUTA PARA PODER COPIAR EL DIRECTOIRO A LA CARPETA DE LA MOTO
                path1 = archivo.getAbsolutePath();
                //SE ALMACENA EL PARENT PARA LAS NUEVAS BUSQUEDAS
                dir = archivo.getParent();
                //SE LE PONE EL NOMBRE A LA IMAGEN....
                //IMPLEMNTAR QUE SOLO MUESTRE EL NOMBRE SIN LA EXT. Y LUEGO PARA GUARDAR 
                //SE CONCATENAN AMBOS
                //SE MOSTRARA SOLO EL NOMBRE Y LA EXTENSION SE GUARDA PARA QUE NO SEA MODIFICADA
                txtImg1.setText( nombre(archivo.getName()) );
                ext1 = ext( archivo.getName() );
                //CUANDO SE VALLA A GUARDAR SE COGE EL NOMBRE DEL TXT Y SE LE AGREGA LA EXT GUARDADA
            }
        }
    }//GEN-LAST:event_btnBu_Ima1ActionPerformed

    private void btnBu_Ima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBu_Ima2ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File(dir));
        fc.setFileFilter(new FileNameExtensionFilter("Archivos de Imagen", "jpg", "jpeg", "png", "gif"));
        fc.setDialogTitle("Buscador de imagenes");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        int status = fc.showOpenDialog(this);
        if(status == JFileChooser.APPROVE_OPTION){
            File archivo = fc.getSelectedFile();
            if(archivo != null){
                ImageIcon icon = new ImageIcon(archivo.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblImg2.getWidth(), lblImg2.getHeight(), Image.SCALE_DEFAULT));
                lblImg2.setText(null);
                lblImg2.setIcon(icono);
                path2 = archivo.getAbsolutePath();
                dir = archivo.getParent();
                txtImg2.setText( nombre(archivo.getName()) );
                ext2 = ext( archivo.getName() );
            }
        }
    }//GEN-LAST:event_btnBu_Ima2ActionPerformed

    private void btnBu_Ima3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBu_Ima3ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File(dir));
        fc.setFileFilter(new FileNameExtensionFilter("Archivos de Imagen", "jpg", "jpeg", "png", "gif"));
        fc.setDialogTitle("Buscador de imagenes");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        int status = fc.showOpenDialog(this);
        if(status == JFileChooser.APPROVE_OPTION){
            File archivo = fc.getSelectedFile();
            if(archivo != null){
                ImageIcon icon = new ImageIcon(archivo.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblImg3.getWidth(), lblImg3.getHeight(), Image.SCALE_DEFAULT));
                lblImg3.setText(null);
                lblImg3.setIcon(icono);
                path3 = archivo.getAbsolutePath();
                dir = archivo.getParent();
                txtImg3.setText( nombre(archivo.getName()) );
                ext3 = ext( archivo.getName() );
            }
        }
    }//GEN-LAST:event_btnBu_Ima3ActionPerformed

    private void btnBu_Ima4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBu_Ima4ActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new java.io.File(dir));
        fc.setFileFilter(new FileNameExtensionFilter("Archivos de Imagen", "jpg", "jpeg", "png", "gif"));
        fc.setDialogTitle("Buscador de imagenes");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setMultiSelectionEnabled(false);
        int status = fc.showOpenDialog(this);
        if(status == JFileChooser.APPROVE_OPTION){
            File archivo = fc.getSelectedFile();
            if(archivo != null){
                ImageIcon icon = new ImageIcon(archivo.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblImg4.getWidth(), lblImg4.getHeight(), Image.SCALE_DEFAULT));
                lblImg4.setText(null);
                lblImg4.setIcon(icono);
                path4 = archivo.getAbsolutePath();
                dir = archivo.getParent();
                txtImg4.setText( nombre(archivo.getName()) );
                ext4 = ext( archivo.getName() );
            }
        }
    }//GEN-LAST:event_btnBu_Ima4ActionPerformed

    private void txtCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCCKeyTyped
         //permite solo numeros
        char caracter = evt.getKeyChar();
        String c = "" + caracter;
        if(!numeros.contains(c)){
            evt.consume();  
        }
        int numero = (int)(caracter);
        if(numero == 10){
           txtLinea.requestFocus();
        }
    }//GEN-LAST:event_txtCCKeyTyped

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
           txtMarca.requestFocus();
        }
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
           txtModelo.requestFocus();
        }
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        String c = "" + caracter;
        if(!numeros.contains(c)){
            evt.consume();  
        }
        if(numero == 10){
           txtCC.requestFocus();
        } 
    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtLineaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLineaKeyTyped
         char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
           txtColor.requestFocus();
        }
    }//GEN-LAST:event_txtLineaKeyTyped

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
           btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_txtColorKeyTyped

    private void btnGuardarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
           btnGuardar.doClick();
        }
    }//GEN-LAST:event_btnGuardarKeyTyped

    private void btnSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
           btnSalir.doClick();
        }
    }//GEN-LAST:event_btnSalirKeyTyped

    private void txtPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyReleased
        txtPlaca.setText(txtPlaca.getText().toUpperCase());
    }//GEN-LAST:event_txtPlacaKeyReleased
    //CARGA IMAGEN AL DAR CLICK SOBRE ELLA
    private void lblImg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg1MouseClicked
        int end = path1.lastIndexOf("\\");
        String subStringSN = path1.substring( 0, end );
        padre = subStringSN;
        VentanaPrincipal vp = new VentanaPrincipal(this, true, padre, path1);
        vp.setVisible(true);
    }//GEN-LAST:event_lblImg1MouseClicked

    private void lblImg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg2MouseClicked
        int end = path2.lastIndexOf("\\");
        String subStringSN = path2.substring( 0, end );
        padre = subStringSN;
        VentanaPrincipal vp = new VentanaPrincipal(this, true, padre, path2);
        vp.setVisible(true);
    }//GEN-LAST:event_lblImg2MouseClicked

    private void lblImg3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg3MouseClicked
        int end = path3.lastIndexOf("\\");
        String subStringSN = path3.substring( 0, end );
        padre = subStringSN;
        VentanaPrincipal vp = new VentanaPrincipal(this, true, padre, path3);
        vp.setVisible(true);
    }//GEN-LAST:event_lblImg3MouseClicked

    private void lblImg4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg4MouseClicked
        int end = path4.lastIndexOf("\\");
        String subStringSN = path4.substring( 0, end );
        padre = subStringSN;
        VentanaPrincipal vp = new VentanaPrincipal(this, true, padre, path4);
        vp.setVisible(true);
    }//GEN-LAST:event_lblImg4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_Moto dialog = new JDialog_Moto(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBu_Ima1;
    private javax.swing.JButton btnBu_Ima2;
    private javax.swing.JButton btnBu_Ima3;
    private javax.swing.JButton btnBu_Ima4;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg4;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtImg1;
    private javax.swing.JTextField txtImg2;
    private javax.swing.JTextField txtImg3;
    private javax.swing.JTextField txtImg4;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    private boolean guardar() {
        boolean rpta = false;
        moto mot = new moto();
        mot.setPlaca(txtPlaca.getText());
        mot.setMarca(txtMarca.getText());
        mot.setLinea(txtLinea.getText());
        if(!"".equals(txtModelo.getText())){
             mot.setModelo(Integer.parseInt(txtModelo.getText()));
        }
        if(!"".equals(txtCC.getText())){
             mot.setCilindraje(Integer.parseInt(txtCC.getText()));
        }
        mot.setColor(txtColor.getText());
        if(!"".equals(jLabel1.getText())){
            mot.setId(Double.parseDouble(jLabel1.getText()));
        }
        
        if(con.verificarMoto(mot) == false){//verifica que la moto no exista ya en la base de datos
            if(con.guardarMoto(mot)){
                btnGuardar.setEnabled(false);
                JOptionPane.showMessageDialog(this,"Datos Guardados");
                jPanel1.setEnabled(false);
                rpta = true;
            }
        }else{
             JOptionPane.showMessageDialog(this,"La moto de placas: "+ mot.getPlaca() + " y marca: " + mot.getMarca() +" ya existe\nLa id de el Dueño es: " + mot.getId());
             //si la moto ya existe, que me mande a otra ventana donde pueda ver los datos completos del cliente
             //para cambiarle el propietario. solo se alteraria el campo id de la tabla de motos
        }
        return rpta;
    }

    private void guardar_img_dir() {
        //CREA UNA CARPETA NOMBRADA CON LA PLACA DE LA MOTO
        //ALLI ES DONDE SE GUARDARAN LAS IMAGENES SELECCIONADAS
        //en la nueva ruta es donde se creara la carpeta
        String newRuta = directorio + txtPlaca.getText().trim();
        File folder = new File(newRuta);
        if(!folder.exists()){//si el directorio que hemos instanciado no existe
            folder.mkdir();//que la cree
            if( !"".equals(txtImg1.getText()) ){
                //COMO SE GUARDAN NUEVOS ARCHIVOS, SE TOMA LA NUEVA RUTA
                //SE DEBE COPIAR LA IMAGEN ANTES DE GUARDARLA EN LA BASE DE DATOS
               //SE MANDA EL ORIGEN, LA NUEVA RUTA MAS EL NOMBRE Y SE LE AGREGA LA EXTENSION 
                copyFile(path1, newRuta + "\\" + txtImg1.getText().trim() + ext1);
                imagenes img = new imagenes();
                img.setNombre( txtImg1.getText().trim() + ext1 );
                img.setPlaca( txtPlaca.getText().trim() );
                img.setRuta(newRuta + "\\" + txtImg1.getText().trim() + ext1);
                if( con.salvar(img) == false ){
                    JOptionPane.showMessageDialog(this, "Error guardando la imagen 1", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            if((!"".equals(txtImg2.getText()))){
                copyFile(path2, newRuta + "\\" + txtImg2.getText().trim() + ext2);

                imagenes img = new imagenes();
                img.setNombre( txtImg2.getText().trim() + ext2 );
                img.setPlaca( txtPlaca.getText().trim() );
                img.setRuta(newRuta + "\\" + txtImg2.getText().trim() + ext2);
                if( con.salvar(img) == false){
                    JOptionPane.showMessageDialog(this, "Error guardando la imagen 2", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            if((!"".equals(txtImg3.getText()))){
                copyFile(path3, newRuta + "\\" + txtImg3.getText().trim() + ext3);

                imagenes img = new imagenes();
                img.setNombre( txtImg3.getText().trim() + ext3 );
                img.setPlaca( txtPlaca.getText().trim() );
                img.setRuta(newRuta + "\\" + txtImg3.getText().trim() + ext3);
                if( con.salvar(img) == false){
                    JOptionPane.showMessageDialog(this, "Error guardando la imagen 3", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            if((!"".equals(txtImg4.getText()))){
                copyFile(path4, newRuta + "\\" + txtImg4.getText().trim() + ext4);

                imagenes img = new imagenes();
                img.setNombre( txtImg4.getText().trim() + ext4 );
                img.setPlaca( txtPlaca.getText().trim() );
                img.setRuta(newRuta + "\\" + txtImg4.getText().trim() + ext4);
                if( con.salvar(img) == false ){
                    JOptionPane.showMessageDialog(this, "Error guardando la imagen 4", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "la carpeta "+ newRuta+ " ya existe");
            //pregunte que si quiere eliminarla y crear una nueva o 
            //si escribe sobreescribe la que existe
        }
    }
    ///*************************
    //METODOS USADOS PARA SEPARAR LOS NOMBRES DE LAS EXTENCIONES
    private String nombre(String cadena){
        return cadena.substring(0, caracteres(cadena));
    }
    private String ext(String cadena){
        return cadena.substring(caracteres(cadena));
    }
    private int caracteres(String cadena){
        return cadena.indexOf(".", (cadena.length() - 5));
    }
    //TERMINAN METODOS PARA SEPARAR NOMBRES DE EXTENCIONES
    //*************************
    
    
    private void cerrarControlado(){
        try {
            this.setDefaultCloseOperation(JFrame_Principal.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent evt){
                    confirmarSalida();
                }
            });
            //
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tratando de cerrar el dialog\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    public void confirmarSalida(){
        //que no permita salir si no se ha guardado ningun dato
        if(contador >= 1){
            if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
                this.dispose();
            } 
        }else{
            JOptionPane.showMessageDialog(this, "Aún no ha guardado ningún dato.");
        }
    }
    
    public void copyFile(String origen, String destino){
//        se copia todo siempre y cuando sea un archivo
//        el nombre es obligatorio y no tiene que ser el mismo que el de origen
//        para el nombre destino se debe especificar el tipo de archivo a copiar
        Path FROM = Paths.get(origen);
        Path TO = Paths.get(destino);
        //sobreescribir el fichero de destino si existe y copiar
        //los atributos, incluyendo los permisos rwx
        try {
            CopyOption[] option = new CopyOption[]{
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.COPY_ATTRIBUTES
            };
            Files.copy(FROM, TO, option); 
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error guardando la imagen 1\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
