
package View;

import Task.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Gomez
 */
public final class JFrame_Principal extends javax.swing.JFrame {
    Conexion con;
    //alarma2
    Timer timer;
    int counter1 = 0;
    Date fecha;
    boolean finTarea = false;
    
    private String usuario;
    /**
     * Creates new form vista
     */
    public JFrame_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        //En el titulo controlo las versiones facilmente, la ultima version estable es 1.5.0.4
        //pero la actualizare y le cambiare a 6
        setTitle("Home TecSoft V1.6");
        cargar_imagen();
        btnCliente.requestFocus();
        con = new Conexion();
        con.conectar();
        cerrarControlado();
        alarma();
    }
    //este contructor es llamado solo desde el login
    public JFrame_Principal(String usuario){
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        jLabel3.setText(usuario);
        //En el titulo controlo las verisones facilmente, la ultima version estable es 1.5.0.4
        //pero la actualizare y le cambiare a 6
        setTitle("Home TecSoft V1.6");
        cargar_imagen();
        btnCliente.requestFocus();
        con = new Conexion();
        con.conectar();
        cerrarControlado();
        alarma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSer_Temp = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnServicio = new javax.swing.JButton();
        btnAdd_Ser = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblImg1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setResizable(false);

        btnSer_Temp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart_go.png"))); // NOI18N
        btnSer_Temp.setText("Servicio Temporal");
        btnSer_Temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSer_TempActionPerformed(evt);
            }
        });
        btnSer_Temp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSer_TempKeyTyped(evt);
            }
        });

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_add.png"))); // NOI18N
        btnCliente.setText("Nuevo Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        btnCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnClienteKeyTyped(evt);
            }
        });

        btnServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cart_add.png"))); // NOI18N
        btnServicio.setText("Prestar Servicio");
        btnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicioActionPerformed(evt);
            }
        });
        btnServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnServicioKeyTyped(evt);
            }
        });

        btnAdd_Ser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        btnAdd_Ser.setText("Agregar Servicio");
        btnAdd_Ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd_SerActionPerformed(evt);
            }
        });
        btnAdd_Ser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnAdd_SerKeyTyped(evt);
            }
        });

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book.png"))); // NOI18N
        btnAgenda.setText("Agenda");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        btnAgenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnAgendaKeyTyped(evt);
            }
        });

        btnInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/report.png"))); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        btnInformes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnInformesKeyTyped(evt);
            }
        });

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cog_go.png"))); // NOI18N
        btnConfig.setText("Configuracion");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });
        btnConfig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnConfigKeyTyped(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        btnSalir.setText("Terminar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnSalirKeyTyped(evt);
            }
        });

        lblImg1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/group_go.png"))); // NOI18N
        jButton1.setText("Ver Clientes");
        jButton1.setToolTipText("ver, editar y eliminar clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo2Reducido.png"))); // NOI18N
        jLabel1.setText("\n");

        jLabel2.setText("Desarrollado Por: A.G");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/status_online.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paintcan.png"))); // NOI18N
        jButton2.setText("Aceite");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd_Ser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSer_Temp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblImg1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSer_Temp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAdd_Ser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSer_TempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSer_TempActionPerformed
        mostrarServicio_Temp();
    }//GEN-LAST:event_btnSer_TempActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        //invoca el dialogo para agregar un nuevo cliente
        JDialog_Cliente cliente = new JDialog_Cliente(this, true, con);
        cliente.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicioActionPerformed
      //JDialog_Servicio servicio = new JDialog_Servicio(this, true, con);
        //servicio.setVisible(true);
        JFrame_Servicio servicio = new JFrame_Servicio(con, usuario);
        servicio.setVisible(true);
    }//GEN-LAST:event_btnServicioActionPerformed

    private void btnAdd_SerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd_SerActionPerformed
        JDialog_Lista_Ser lista = new JDialog_Lista_Ser(this, true, con);
        lista.setVisible(true);
    }//GEN-LAST:event_btnAdd_SerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog_Bus_Cli elegir = new  JDialog_Bus_Cli(this, true, con);
        elegir.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
            if(con != null){
                con = null;
            }
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        // AGENDA
        JDialog_Agenda agenda = new JDialog_Agenda(this, true, con);
        agenda.setVisible(true);
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        //Reportes
        JDialog_Reporte rep = new JDialog_Reporte(this, true, con);
        rep.setVisible(true);
    }//GEN-LAST:event_btnInformesActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // por ahora la configuracion solo sera asignar un nuevo acceso al sistema
        JDialog_Conf conf = new JDialog_Conf(this, true, con);
        conf.setVisible(true);
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClienteKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnCliente.doClick();
        }
    }//GEN-LAST:event_btnClienteKeyTyped

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyTyped

    private void btnServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnServicioKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnServicio.doClick();
        }
    }//GEN-LAST:event_btnServicioKeyTyped

    private void btnSer_TempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSer_TempKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnSer_Temp.doClick();
        }
    }//GEN-LAST:event_btnSer_TempKeyTyped

    private void btnAdd_SerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdd_SerKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnAdd_Ser.doClick();
        }
    }//GEN-LAST:event_btnAdd_SerKeyTyped

    private void btnAgendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgendaKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnAgenda.doClick();
        }
    }//GEN-LAST:event_btnAgendaKeyTyped

    private void btnInformesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnInformesKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnInformes.doClick();
        }
    }//GEN-LAST:event_btnInformesKeyTyped

    private void btnConfigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfigKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnConfig.doClick();
        }
    }//GEN-LAST:event_btnConfigKeyTyped

    private void btnSalirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyTyped
        char caracter = evt.getKeyChar();
        int numero = (int)(caracter);
        if(numero == 10){
                btnSalir.doClick();
        }
    }//GEN-LAST:event_btnSalirKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDialog_Aceite aceite = new JDialog_Aceite(this, true, con);
        aceite.setVisible(true);    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        JOptionPane.showMessageDialog(this, "Desarrollado por Andrés Gómez. Revisa más de mis proyectos en GitHub\n"
                + "http://www.github.com/AndresG-8");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd_Ser;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSer_Temp;
    private javax.swing.JButton btnServicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblImg1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Er6n.png"));
        return retValue;
    }
    
    private void mostrarServicio_Temp() {
        //boton que invoca el dialog de servicios temporales
        JDialog_Servicio_Temp ser = new JDialog_Servicio_Temp(this, false, con);
        ser.setVisible(true);
    }
        
    private void cargar_imagen(){
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Launcher 2013-08-06 17-09-41-990.jpg"))); // NOI18N      
        //lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Moto_Pique.jpg")));
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/Pique.jpg"));
        Icon iconito = new ImageIcon(icono.getImage().getScaledInstance(lblImg1.getWidth(), lblImg1.getHeight(), Image.SCALE_DEFAULT));
        lblImg1.setIcon(iconito);
    }
     
    public void cerrarControlado(){
        try {
            this.setDefaultCloseOperation(JFrame_Principal.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent evt){
                    confirmarSalida();
                }
            });
            //
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    public void confirmarSalida(){
        
        if(JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?", "salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0){
            if(con != null){
                con = null;
            }
            System.exit(0);
        }
    }

    public void alarma(){
        //se crea una tarea con un timer.
        timer = new Timer();
        //la tarea se ejecuta pasados 1 segundos y luego periodicamente cada segundo, claro. si no se cancela
        timer.schedule(new Tarea(), 1000, 500);
    }
    
    class Tarea extends TimerTask{
        public void run(){
            int rpta = 0;
            int rpta_aceite = 0;
            try {
                rpta = con.cargar_alarma("select nombre, descripcion, fecha_inicial, fecha_entrega, hora_entrega FROM agenda where fecha_entrega = CONVERT(DATE, GETDATE())");
                rpta_aceite = con.cargar_alarma("SELECT [cod_aceite] ,[aceite],[marca],[cantidad],[ult_cambio],[km_actual],[estado],[km_prox_cambio]\n" +
                        " ,[fecha_prox_cambio],[placa],[nombre] FROM [dbo].[aceite] \n" +
                        " WHERE fecha_prox_cambio = CONVERT(DATE, GETDATE())");
                if( rpta != 0 | rpta_aceite != 0){
                    JOptionPane.showMessageDialog(null, "Tiene " + rpta + " citas y "+rpta_aceite+" cambios"
                            + " de aceite\n programados para el día de hoy ");
                }else{
                    JOptionPane.showMessageDialog(null, "No tiene citas para hoy");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error con la alarma\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE );
            }
            this.cancel();
            timer.cancel();
        }
    }
}
